# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa38dc4e141b68132699c9f03f3fe5ccbe6c6f0dbeb181e5d510b7872a907953a6aa87f090261b6d16aa0a989db8b509c8500d0b881fe1a1a4bb2537d5d7613b

test:
  secret_key_base: ec3b2591abdf8e7dad8e8882fdecf05c62a7fe179087c19916caebc7f71d78894d38920cc497dcd6b003cb99add25a27d3e62a858176cbefa00acb745de89ca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
